import { describe, expect, it } from 'vitest';
import seed from '../../../seed/spreadsheet-history.json';
import { split } from '../engine/split';
import { toEngineInputs } from '../ui/formState';
import { createLocalStore } from './localStore';
import type { SavedCycle } from './types';

/**
 * Golden test for `seed/spreadsheet-history.json` — the seven cycles lifted out
 * of the owner's original spreadsheet (generated by `tools/seed_history.py`).
 *
 * It pins two things: that the file still imports and splits, and the exact
 * restated share of each cycle. The restatement differs from the spreadsheet's
 * own arithmetic in two ways, both deliberate:
 *
 *   D-01 — fixed charges are shared by consumption ratio, not ₹25 each;
 *   D-09 — the motor is shared load, not first-floor load.
 */

const cycles = (seed as { cycles: SavedCycle[] }).cycles;

/** Rupees the FIRST FLOOR owes, restated under the current rules. */
const EXPECTED_FIRST_FLOOR: Record<string, number> = {
  'Apr-May-25': 1414.0,
  'Jun-Jul-25': 1438.01,
  'Aug-Sep-25': 1515.92,
  'Oct-Nov-25': 1487.36,
  'Dec-Jan-26': 702.99,
  'Feb-Mar-26': 1256.51,
  'Apr-May-26': 2000.34,
};

const run = (cycle: SavedCycle) => {
  const { bill, households, options } = toEngineInputs(cycle);
  return split(bill, households, options);
};

describe('spreadsheet history seed', () => {
  it('carries all seven cycles', () => {
    expect(cycles).toHaveLength(7);
    expect(cycles.map((c) => c.bill.billingMonth)).toEqual(Object.keys(EXPECTED_FIRST_FLOOR));
  });

  it.each(cycles)('$bill.billingMonth splits exactly', (cycle) => {
    const result = run(cycle);

    // Nothing to report: a bill entered as its own total cannot disagree with
    // the printed payable, the sub-meters never exceed the official reading,
    // and the ground floor's residual is expected rather than anomalous.
    expect(result.warnings).toEqual([]);
    expect(result.payable).toBe(Math.round(cycle.bill.printedPayable! * 100));

    const sum = result.shares.reduce((a, s) => a + s.total, 0);
    expect(sum).toBe(result.payable);

    const first = result.shares.find((s) => s.householdId === 'first')!;
    expect(first.total).toBe(
      Math.round(EXPECTED_FIRST_FLOOR[cycle.bill.billingMonth] * 100),
    );
  });

  it('is importable by the History panel as-is', () => {
    const store = createLocalStore();
    expect(store.importAll(JSON.stringify(seed), 'replace')).toBe(7);
    expect(store.list().map((c) => c.label)).toContain('Apr-May-26 (from the spreadsheet)');
    // Newest first, so the last cycle the owner filled in is on top.
    expect(store.list()[0].bill.billingMonth).toBe('Apr-May-26');
  });

  it('attributes the motor as shared load, not to the first floor', () => {
    for (const cycle of cycles) {
      const result = run(cycle);
      expect(result.commonUnits).toBeGreaterThan(0);
      for (const share of result.shares) expect(share.commonUnits).toBeGreaterThan(0);
    }
  });
});
